
version: '3.3'

services:

  db:
    build: ./db
    container_name: postgres
    volumes:
      - ./data:/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  
    ports:
      - 5432:5432
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
